name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from yamashita-kkkk
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: yamashita-kkkk
