name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request review
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers: ['yamashita-kkkk']
            });
