name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize] # プルリクが作成されたときや更新されたとき

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request review from yamashita-kkkk
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['yamashita-kkkk']
            })
